links:
  rails_tutorial:
    home_page: https://www.railstutorial.org/
    help_page: http://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book
  gravatar: "http://gravatar.com/emails"
validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 8

remember_me: "1"
per_page: 5
